return {
  require 'plugins.autopairs',
  require 'plugins.blink',
  require 'plugins.bufferline',
  require 'plugins.catppuccin',
  require 'plugins.codecompanion',
  require 'plugins.conform',
  require 'plugins.flash',
  require 'plugins.gitsigns',
  require 'plugins.indent-blankline',
  require 'plugins.lspconfig',
  require 'plugins.lualine',
  require 'plugins.lazydev',
  require 'plugins.mason',
  require 'plugins.mini',
  require 'plugins.neo-tree',
  require 'plugins.neoscroll',
  require 'plugins.noice',
  require 'plugins.project',
  require 'plugins.telescope',
  require 'plugins.todo-comments',
  require 'plugins.treesitter',
  require 'plugins.trouble',
  require 'plugins.which-key',
  require 'plugins.windsurf',

  'NMAC427/guess-indent.nvim',
}
